import type { Destination, DestinationCategory } from '../types/destination';
import jharkhandGeoJsonRaw from './jharkhandDistrictsGeoJSON.json';

export const JHARKHAND_DISTRICTS_GEOJSON = jharkhandGeoJsonRaw as unknown as GeoJSON.FeatureCollection;

export const JHARKHAND_MAP_CONFIG = {
  CENTER: [23.65, 85.50] as [number, number],
  DEFAULT_ZOOM: 7.6,
  MIN_ZOOM: 7,
  MAX_ZOOM: 16,
  BOUNDS: [
    [21.80, 83.20],
    [25.40, 88.00],
  ] as [[number, number], [number, number]],
  MAX_BOUNDS_VISCOSITY: 0.9,
};

export interface DistrictInfo {
  name: string;
  hq: string;
  center: [number, number];
  zoom: number;
  description: string;
  keyAttractions: string[];
  polygon: [number, number][];
}

export const CATEGORY_THEMES: Record<
  DestinationCategory,
  {
    label: string;
    color: string;
    bgBadge: string;
    textColor: string;
    svgIcon: string;
  }
> = {
  waterfall: {
    label: 'Waterfalls',
    color: '#0284c7', // Sky blue
    bgBadge: 'bg-sky-100 text-sky-800 border-sky-300',
    textColor: 'text-sky-700',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v6"/><path d="m4.93 10.93 4.24-4.24"/><path d="M2 18h20"/><path d="M20 10a8 8 0 0 0-16 0"/><path d="M7 14v4"/><path d="M12 14v4"/><path d="M17 14v4"/></svg>`,
  },
  wildlife: {
    label: 'Wildlife & Sanctuaries',
    color: '#15803d', // Emerald green
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    textColor: 'text-emerald-700',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a9 9 0 0 0-9 9c0 4.97 4.03 9 9 9 3.5 0 6.5-2 7.8-5"/><path d="M12 7v5l3 3"/><path d="M16 4h4v4"/><path d="M20 4l-5 5"/></svg>`,
  },
  heritage: {
    label: 'Heritage & History',
    color: '#b45309', // Amber bronze
    bgBadge: 'bg-amber-100 text-amber-900 border-amber-300',
    textColor: 'text-amber-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="22" x2="21" y2="22"/><line x1="6" y1="18" x2="6" y2="11"/><line x1="10" y1="18" x2="10" y2="11"/><line x1="14" y1="18" x2="14" y2="11"/><line x1="18" y1="18" x2="18" y2="11"/><polygon points="12 2 20 7 4 7"/></svg>`,
  },
  religious: {
    label: 'Sacred Shrines',
    color: '#c2410c', // Terracotta orange
    bgBadge: 'bg-orange-100 text-orange-900 border-orange-300',
    textColor: 'text-orange-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l2 4 4 1-3 3 1 4-4-2-4 2 1-4-3-3 4-1z"/><path d="M12 14v8"/><path d="M8 22h8"/></svg>`,
  },
  tribal_culture: {
    label: 'Tribal Culture & Arts',
    color: '#a21caf', // Magenta purple
    bgBadge: 'bg-fuchsia-100 text-fuchsia-900 border-fuchsia-300',
    textColor: 'text-fuchsia-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="m4.93 4.93 4.24 4.24"/><path d="m14.83 9.17 4.24-4.24"/><path d="m14.83 14.83 4.24 4.24"/><path d="m9.17 14.83-4.24 4.24"/></svg>`,
  },
  adventure: {
    label: 'Adventure & Hills',
    color: '#ea580c', // Deep orange
    bgBadge: 'bg-amber-100 text-amber-900 border-amber-300',
    textColor: 'text-amber-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/></svg>`,
  },
  eco: {
    label: 'Eco Tourism & Lakes',
    color: '#059669', // Teal green
    bgBadge: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    textColor: 'text-emerald-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></svg>`,
  },
  craft: {
    label: 'Artisans & Crafts',
    color: '#b91c1c', // Rust red
    bgBadge: 'bg-red-100 text-red-900 border-red-300',
    textColor: 'text-red-800',
    svgIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>`,
  },
};

/** All 24 Districts of Jharkhand with geographic coordinates and boundaries */
export const JHARKHAND_DISTRICTS_DATA: Record<string, DistrictInfo> = {
  Ranchi: {
    name: 'Ranchi',
    hq: 'Ranchi',
    center: [23.3441, 85.3096],
    zoom: 10.5,
    description: 'Capital city & City of Waterfalls (Hundru, Dassam, Jonha, Rock Garden).',
    keyAttractions: ['Hundru Falls', 'Dassam Falls', 'Jonha Falls', 'Rock Garden', 'Tribal Museum', 'Pahari Mandir', 'Tagore Hill', 'Jagannath Temple'],
    polygon: [
      [23.65, 85.10], [23.62, 85.65], [23.35, 85.80], [23.10, 85.60], [23.08, 85.15], [23.30, 84.95], [23.65, 85.10],
    ],
  },
  Latehar: {
    name: 'Latehar',
    hq: 'Latehar',
    center: [23.7447, 84.4983],
    zoom: 10,
    description: 'Queen of Chotanagpur (Netarhat), Betla Tiger Reserve & Lodh Falls.',
    keyAttractions: ['Netarhat Sunrise Deck', 'Betla National Park', 'Lodh Falls', 'Lower Ghaghri', 'Upper Ghaghri', 'Magnolia Point'],
    polygon: [
      [24.05, 84.05], [24.00, 84.70], [23.55, 84.85], [23.35, 84.30], [23.60, 84.00], [24.05, 84.05],
    ],
  },
  Ramgarh: {
    name: 'Ramgarh',
    hq: 'Ramgarh Cantonment',
    center: [23.6380, 85.5126],
    zoom: 11,
    description: 'Serpentine Patratu Valley reservoir & sacred Rajrappa Maa Chhinnamasta shrine.',
    keyAttractions: ['Patratu Valley', 'Patratu Dam Lake', 'Rajrappa Temple', 'Damodar-Bhairavi Sangam'],
    polygon: [
      [23.80, 85.35], [23.78, 85.80], [23.50, 85.75], [23.45, 85.30], [23.80, 85.35],
    ],
  },
  Deoghar: {
    name: 'Deoghar',
    hq: 'Deoghar',
    center: [24.4860, 86.6980],
    zoom: 11,
    description: 'Spiritual capital of Jharkhand, sacred Baidyanath Jyotirlinga & Trikut Pahar ropeway.',
    keyAttractions: ['Baidyanath Dham', 'Trikut Pahar', 'Naulakha Temple', 'Tapovan Caves'],
    polygon: [
      [24.65, 86.50], [24.68, 86.95], [24.30, 87.05], [24.25, 86.60], [24.65, 86.50],
    ],
  },
  'East Singhbhum': {
    name: 'East Singhbhum',
    hq: 'Jamshedpur',
    center: [22.8050, 86.2029],
    zoom: 10.5,
    description: 'Steel City Jamshedpur, Dalma Elephant Reserve, Dimna Lake & Ghatshila hills.',
    keyAttractions: ['Dalma Wildlife Sanctuary', 'Dimna Lake', 'Jubilee Park', 'Ghatshila Burudi Lake', 'Dharagiri Falls'],
    polygon: [
      [23.05, 86.15], [23.00, 86.65], [22.45, 86.85], [22.35, 86.20], [22.75, 86.05], [23.05, 86.15],
    ],
  },
  'West Singhbhum': {
    name: 'West Singhbhum',
    hq: 'Chaibasa',
    center: [22.3100, 85.3400],
    zoom: 9.8,
    description: 'Vast Saranda primeval sal forest (Land of 700 Hills) & Hirni Waterfalls.',
    keyAttractions: ['Saranda Forest', 'Hirni Falls', 'Lupungutu Springs', 'Chaibasa Rungta Park'],
    polygon: [
      [22.85, 85.20], [22.80, 85.90], [22.05, 85.95], [21.95, 85.10], [22.35, 85.00], [22.85, 85.20],
    ],
  },
  'Saraikela Kharsawan': {
    name: 'Saraikela Kharsawan',
    hq: 'Saraikela',
    center: [22.7000, 85.9300],
    zoom: 10.5,
    description: 'Cradle of UNESCO-recognized Chhau martial dance & Chandil Dam water sports.',
    keyAttractions: ['Saraikela Palace', 'Chhau Dance Academy', 'Chandil Dam', 'Palna Dam'],
    polygon: [
      [23.10, 85.80], [23.05, 86.25], [22.60, 86.15], [22.55, 85.70], [22.90, 85.65], [23.10, 85.80],
    ],
  },
  Khunti: {
    name: 'Khunti',
    hq: 'Khunti',
    center: [23.0782, 85.2778],
    zoom: 10.8,
    description: 'Birthplace of freedom icon Bhagwan Birsa Munda (Ulihatu) & Panchghagh cascades.',
    keyAttractions: ['Birsa Munda Complex Ulihatu', 'Panchghagh Falls', 'Perwaghagh Falls', 'Deer Park Khunti'],
    polygon: [
      [23.25, 85.10], [23.20, 85.65], [22.85, 85.60], [22.75, 85.05], [23.25, 85.10],
    ],
  },
  Hazaribagh: {
    name: 'Hazaribagh',
    hq: 'Hazaribagh',
    center: [23.9950, 85.3580],
    zoom: 10.5,
    description: 'City of Thousand Gardens, Canary Hill, Sohrai GI Art galleries & National Park.',
    keyAttractions: ['Hazaribagh National Park', 'Canary Hill', 'Konar Dam', 'Sanskriti Sohrai Archive'],
    polygon: [
      [24.30, 85.15], [24.25, 85.75], [23.75, 85.85], [23.70, 85.10], [24.30, 85.15],
    ],
  },
  Dhanbad: {
    name: 'Dhanbad',
    hq: 'Dhanbad',
    center: [23.7957, 86.4304],
    zoom: 10.8,
    description: 'Coal capital with scenic Maithon Dam (Lake of Flowers), Panchet Dam & Topchanchi.',
    keyAttractions: ['Maithon Dam & Kalyaneshwari', 'Topchanchi Lake', 'Panchet Dam', 'Bhatinda Falls'],
    polygon: [
      [24.05, 86.20], [24.00, 86.85], [23.65, 86.90], [23.60, 86.15], [24.05, 86.20],
    ],
  },
  Bokaro: {
    name: 'Bokaro',
    hq: 'Bokaro Steel City',
    center: [23.6693, 86.1511],
    zoom: 11,
    description: 'Planned industrial green city, Tenughat Dam & Jawaharlal Nehru Biological Park.',
    keyAttractions: ['Garga Dam & Eco Park', 'Tenughat Dam', 'City Park & Zoo', 'Pupunki Ashram'],
    polygon: [
      [23.85, 85.75], [23.82, 86.35], [23.50, 86.30], [23.52, 85.70], [23.85, 85.75],
    ],
  },
  Giridih: {
    name: 'Giridih',
    hq: 'Giridih',
    center: [24.1800, 86.3000],
    zoom: 10.5,
    description: 'Parasnath Hill (Shikharji, highest peak at 1,365m), Usri Falls & Khandoli Dam.',
    keyAttractions: ['Parasnath Shikharji Peak', 'Usri Falls', 'Khandoli Adventure Dam', 'Harihar Dham'],
    polygon: [
      [24.45, 85.80], [24.40, 86.55], [23.90, 86.40], [23.85, 85.85], [24.45, 85.80],
    ],
  },
  Koderma: {
    name: 'Koderma',
    hq: 'Koderma',
    center: [24.4670, 85.5937],
    zoom: 11,
    description: 'Mica Capital with panoramic Tilaiya Dam reservoir & Dhwajadhari Hill sanctuary.',
    keyAttractions: ['Tilaiya Dam', 'Koderma Wildlife Sanctuary', 'Dhwajadhari Hill', 'Urwan Tourist Complex'],
    polygon: [
      [24.70, 85.40], [24.68, 85.85], [24.25, 85.80], [24.28, 85.35], [24.70, 85.40],
    ],
  },
  Chatra: {
    name: 'Chatra',
    hq: 'Chatra',
    center: [24.2084, 84.8718],
    zoom: 10.5,
    description: 'Maa Bhadrakali Itkhori holy sangam, Kunda Fort ruins & Tamasin forest waterfalls.',
    keyAttractions: ['Bhadrakali Temple Itkhori', 'Kunda Fort', 'Tamasin Falls', 'Maludah Falls'],
    polygon: [
      [24.55, 84.60], [24.50, 85.25], [23.95, 85.20], [23.98, 84.55], [24.55, 84.60],
    ],
  },
  Palamu: {
    name: 'Palamu',
    hq: 'Medininagar (Daltonganj)',
    center: [24.0384, 84.0697],
    zoom: 10.2,
    description: 'Historic 16th-century Chero Dynasty Palamu Forts & Auranga-Koel river basin.',
    keyAttractions: ['Old & New Palamu Forts', 'Shahpur Fort', 'Betla Tiger Corridor', 'Koyal River View'],
    polygon: [
      [24.45, 83.85], [24.40, 84.50], [23.75, 84.45], [23.80, 83.80], [24.45, 83.85],
    ],
  },
  Garhwa: {
    name: 'Garhwa',
    hq: 'Garhwa',
    center: [24.1800, 83.8000],
    zoom: 10.2,
    description: 'Sukhaldari waterfalls on Kanhar River & ancient pure gold idol at Nagar Untari.',
    keyAttractions: ['Sukhaldari Falls', 'Parasdiha Falls', 'Radha Krishna Temple Nagar Untari', 'Ganga Dam'],
    polygon: [
      [24.50, 83.35], [24.45, 84.00], [23.85, 83.95], [23.90, 83.30], [24.50, 83.35],
    ],
  },
  Gumla: {
    name: 'Gumla',
    hq: 'Gumla',
    center: [23.0428, 84.5422],
    zoom: 10.2,
    description: 'Mythological Anjan Dham (Hanuman Birthplace), Tanginath Dham & UNESCO Navratangarh Fort.',
    keyAttractions: ['Anjan Dham', 'Tanginath Dham', 'Sadni Falls', 'Navratangarh Fort (Sisai)'],
    polygon: [
      [23.45, 84.15], [23.40, 85.05], [22.80, 84.95], [22.82, 84.10], [23.45, 84.15],
    ],
  },
  Lohardaga: {
    name: 'Lohardaga',
    hq: 'Lohardaga',
    center: [23.4357, 84.6811],
    zoom: 11,
    description: 'Kekrang cascades, mineral-rich Bagru Hill plateaus & serene Nandani Dam.',
    keyAttractions: ['Kekrang Falls', 'Bagru Hills', 'Nandani Reservoir', 'Lawapani Falls'],
    polygon: [
      [23.65, 84.50], [23.60, 84.90], [23.25, 84.85], [23.30, 84.45], [23.65, 84.50],
    ],
  },
  Simdega: {
    name: 'Simdega',
    hq: 'Simdega',
    center: [22.6144, 84.5089],
    zoom: 10.5,
    description: 'Cradle of Indian Hockey, Kelaghagh Dam, Dangadi Eco Park & sacred Ramrekha Dham.',
    keyAttractions: ['Kelaghagh Dam & Falls', 'Ramrekha Dham', 'Dangadi Eco Sanctuary', 'Bhanwar Pahar'],
    polygon: [
      [22.95, 84.15], [22.90, 84.85], [22.35, 84.75], [22.40, 84.10], [22.95, 84.15],
    ],
  },
  Dumka: {
    name: 'Dumka',
    hq: 'Dumka',
    center: [24.2677, 87.2497],
    zoom: 10.5,
    description: 'Sub-capital of Jharkhand, Basukinath Shiva Dham, Massanjore Dam & Maluti Temples.',
    keyAttractions: ['Basukinath Dham', 'Massanjore Dam (Canada Dam)', 'Maluti 72 Terracotta Temples', 'Tatloi Hot Spring'],
    polygon: [
      [24.60, 87.00], [24.55, 87.65], [24.00, 87.70], [24.02, 86.95], [24.60, 87.00],
    ],
  },
  Godda: {
    name: 'Godda',
    hq: 'Godda',
    center: [24.8267, 87.2144],
    zoom: 10.8,
    description: 'Sundar Dam eco-retreat, St. Francis Church & sacred Maa Yogini Shrine.',
    keyAttractions: ['Sundar Dam Eco Park', 'Maa Yogini Temple (Barkopa)', 'Lalmatia Coal Range'],
    polygon: [
      [25.15, 87.00], [25.10, 87.55], [24.55, 87.50], [24.60, 86.95], [25.15, 87.00],
    ],
  },
  Sahibganj: {
    name: 'Sahibganj',
    hq: 'Sahibganj',
    center: [25.2425, 87.6416],
    zoom: 10.5,
    description: 'Where the holy Ganga kisses Jharkhand, Rajmahal Fossil Park, Teliagarhi Fort & Udhwa Birds.',
    keyAttractions: ['Rajmahal Fossil Sanctuary', 'Moti Jharna Falls', 'Teliagarhi Historic Fort', 'Udhwa Lake Bird Sanctuary'],
    polygon: [
      [25.40, 87.40], [25.35, 87.95], [24.80, 87.90], [24.85, 87.35], [25.40, 87.40],
    ],
  },
  Pakur: {
    name: 'Pakur',
    hq: 'Pakur',
    center: [24.6340, 87.8493],
    zoom: 11,
    description: 'Historic Martello Tower of 1856 Santhal Hul, Nityakali Mandir & Dhuni hot springs.',
    keyAttractions: ['Martello Tower 1856', 'Nityakali Mandir', 'Hot Springs of Dhuni', 'Shiv Pahar'],
    polygon: [
      [24.85, 87.60], [24.82, 87.98], [24.40, 87.95], [24.42, 87.55], [24.85, 87.60],
    ],
  },
  Jamtara: {
    name: 'Jamtara',
    hq: 'Jamtara',
    center: [23.9600, 86.8000],
    zoom: 11,
    description: 'Parwat Vihar eco-hill, Ladhna Dam water reserve & Ajay-Damodar watershed trails.',
    keyAttractions: ['Parwat Vihar Hill Park', 'Ladhna Dam Boating', 'Mihijam Eco Point'],
    polygon: [
      [24.15, 86.60], [24.12, 87.10], [23.75, 87.05], [23.78, 86.55], [24.15, 86.60],
    ],
  },
};

/**
 * Curated list of verified tourist destinations across all 24 districts of Jharkhand
 * with precise GPS coordinates, real imagery, and full metadata.
 */
export const VERIFIED_JHARKHAND_DESTINATIONS: Destination[] = [
  // ── Ranchi District ────────────────────────────────────────────────────────
  {
    id: 'dest-hundru',
    slug: 'hundru-falls',
    name: 'Hundru Falls',
    short_description: 'Dramatic 98-metre plunge of the Subarnarekha River through ancient Precambrian canyon rocks.',
    description: 'One of the most spectacular waterfalls in Jharkhand, Hundru Falls cascades from a height of 98 metres (322 ft) creating scenic mist pools and water amphitheaters popular for picnics and photography.',
    district: 'Ranchi',
    category: 'waterfall',
    latitude: 23.4475,
    longitude: 85.6542,
    cover_image: '/images/destinations/hundru-falls.jpg',
    gallery: ['/images/destinations/hundru-falls.jpg', '/images/destinations/dassam-falls.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-dassam',
    slug: 'dassam-falls',
    name: 'Dassam Falls',
    short_description: 'Layered natural cascade of the Kanchi River plunging into a pristine emerald canyon pool.',
    description: 'Dassam Falls (also known as Da-song) is an awe-inspiring natural cascade on the Kanchi River where water drops 44 metres across natural rock steps, surrounded by dense Sal forests.',
    district: 'Ranchi',
    category: 'waterfall',
    latitude: 23.1425,
    longitude: 85.4667,
    cover_image: '/images/destinations/dassam-falls.jpg',
    gallery: ['/images/destinations/dassam-falls.jpg'],
    eco_zone: true,
    best_time: 'July to February',
    entry_fee: 15,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-jonha',
    slug: 'jonha-falls',
    name: 'Jonha Falls (Gautamdhara)',
    short_description: 'Stepped rock waterfall linked to Buddhist tradition with 722 steps descending to the river.',
    description: 'Also known as Gautamdhara, Jonha Falls is a sacred hanging-valley waterfall where Lord Buddha is believed to have bathed. Surrounded by scenic hills with an ancient Buddhist shrine at the summit.',
    district: 'Ranchi',
    category: 'waterfall',
    latitude: 23.3444,
    longitude: 85.6083,
    cover_image: '/images/destinations/jonha-falls.jpg',
    gallery: ['/images/destinations/jonha-falls.jpg'],
    eco_zone: true,
    best_time: 'September to February',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-rock-garden',
    slug: 'rock-garden-ranchi',
    name: 'Rock Garden & Kanke Dam',
    short_description: 'Artistic landscaped park crafted from Gonda Hill rocks overlooking Kanke Lake.',
    description: 'Built out of the natural boulders of Gonda Hill, Rock Garden in Ranchi offers panoramic views of Kanke Dam, artistic stone sculptures, waterfalls, and walking trails.',
    district: 'Ranchi',
    category: 'heritage',
    latitude: 23.4022,
    longitude: 85.3186,
    cover_image: '/images/destinations/rock-garden-ranchi.jpg',
    gallery: ['/images/destinations/rock-garden-ranchi.jpg'],
    eco_zone: false,
    best_time: 'October to March',
    entry_fee: 20,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-tribal-museum',
    slug: 'tribal-museum-ranchi',
    name: 'State Tribal Museum, Ranchi',
    short_description: 'Comprehensive cultural archive celebrating the 32 indigenous tribes of Jharkhand.',
    description: 'The Dr. Ramdayal Munda Tribal Welfare Research Institute Museum showcases life-size tribal dwelling dioramas, authentic musical instruments, hunting gear, and traditional Sohrai/Khovar textiles.',
    district: 'Ranchi',
    category: 'tribal_culture',
    latitude: 23.3640,
    longitude: 85.3210,
    cover_image: '/images/destinations/tribal-museum-ranchi.jpg',
    gallery: ['/images/destinations/tribal-museum-ranchi.jpg'],
    eco_zone: false,
    best_time: 'All year',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-jagannath-ranchi',
    slug: 'jagannath-temple-ranchi',
    name: 'Jagannath Temple, Dhurwa',
    short_description: '17th-century hilltop temple built by King Barkagarh Jagannathpur with grand Rath Yatra.',
    description: 'Built in 1691 by King Ani Nath Shahdeo, this architectural marvel sits atop a small hill in Dhurwa, mirroring the architecture of the famous Puri Jagannath Temple.',
    district: 'Ranchi',
    category: 'religious',
    latitude: 23.3139,
    longitude: 85.2819,
    cover_image: '/images/destinations/jagannath-temple.jpg',
    gallery: ['/images/destinations/jagannath-temple.jpg'],
    eco_zone: false,
    best_time: 'All year (June Rath Yatra)',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Latehar District ────────────────────────────────────────────────────────
  {
    id: 'dest-netarhat',
    slug: 'netarhat',
    name: 'Netarhat (Queen of Chotanagpur)',
    short_description: 'Serene pine hill station famed for golden Magnolia Point sunsets and misty dawn vistas.',
    description: 'Nestled at 1,128m elevation, Netarhat is the premier hill retreat of Jharkhand. Features dense pine groves, British-era chalets, Magnolia Point sunset views, and Koel River viewpoints.',
    district: 'Latehar',
    category: 'eco',
    latitude: 23.4790,
    longitude: 84.2640,
    cover_image: '/images/destinations/netarhat.jpg',
    gallery: ['/images/destinations/netarhat.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-betla',
    slug: 'betla-national-park',
    name: 'Betla National Park',
    short_description: 'Primeval tiger reserve with wild elephant herds, bison, and ancient 16th-century Chero forts.',
    description: 'One of India’s earliest Project Tiger reserves, Betla sprawls over 226 sq km of Sal and bamboo forests. Home to elephants, leopards, tigers, gaur, and the iconic twin Chero forts.',
    district: 'Latehar',
    category: 'wildlife',
    latitude: 23.8300,
    longitude: 84.1300,
    cover_image: '/images/destinations/betla-national-park.jpg',
    gallery: ['/images/destinations/betla-national-park.jpg'],
    eco_zone: true,
    best_time: 'November to April',
    entry_fee: 50,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-lodh',
    slug: 'lodh-falls',
    name: 'Lodh Falls (Burha Ghagh)',
    short_description: 'The highest waterfall in Jharkhand, thundering down 143 metres inside deep Sal wilderness.',
    description: 'Burha Ghagh or Lodh Falls is Jharkhand’s tallest waterfall (143 m / 469 ft) on the Burha River. Its roaring cascade can be heard 10 km away during the monsoon.',
    district: 'Latehar',
    category: 'waterfall',
    latitude: 23.6800,
    longitude: 84.2800,
    cover_image: '/images/destinations/lodh-falls.jpg',
    gallery: ['/images/destinations/lodh-falls.jpg'],
    eco_zone: true,
    best_time: 'July to February',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Ramgarh District ────────────────────────────────────────────────────────
  {
    id: 'dest-patratu',
    slug: 'patratu-valley',
    name: 'Patratu Valley & Dam',
    short_description: 'Serpentine hillside roads carving panoramic vistas around a vast sapphire water reservoir.',
    description: 'Famous for its hairpin curves, Patratu Valley features an expansive reservoir with island boating, watersports, sunset viewpoints, and modern lakeside eco-promenades.',
    district: 'Ramgarh',
    category: 'adventure',
    latitude: 23.6380,
    longitude: 85.3610,
    cover_image: '/images/destinations/patratu-valley.jpg',
    gallery: ['/images/destinations/patratu-valley.jpg'],
    eco_zone: true,
    best_time: 'October to February',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-rajrappa',
    slug: 'rajrappa-temple',
    name: 'Rajrappa Maa Chhinnamasta Shrine',
    short_description: 'Venerated Shakti Peeth sanctuary at the sacred confluence of Damodar and Bhairavi rivers.',
    description: 'Rajrappa is a revered pilgrimage destination home to the ancient headless deity Maa Chhinnamasta. The temple sits dramatically over the roaring Bhairavi river gorge.',
    district: 'Ramgarh',
    category: 'religious',
    latitude: 23.6322,
    longitude: 85.7144,
    cover_image: '/images/destinations/rajrappa.jpg',
    gallery: ['/images/destinations/rajrappa.jpg'],
    eco_zone: false,
    best_time: 'All year',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Deoghar District ────────────────────────────────────────────────────────
  {
    id: 'dest-baidyanath',
    slug: 'baidyanath-dham-deoghar',
    name: 'Baidyanath Jyotirlinga Dham',
    short_description: 'One of the twelve sacred Jyotirlingas of Lord Shiva and destination of the world-famous Shravani Mela.',
    description: 'Baidyanath Dham in Deoghar is one of the most venerated Shiva temples in India. The temple complex comprises 22 shrines with the central sanctum dedicated to Baba Baidyanath.',
    district: 'Deoghar',
    category: 'religious',
    latitude: 24.4860,
    longitude: 86.6980,
    cover_image: '/images/destinations/deoghar-baidyanath.jpg',
    gallery: ['/images/destinations/deoghar-baidyanath.jpg'],
    eco_zone: false,
    best_time: 'All year (July-August Shravan)',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-trikut',
    slug: 'trikut-pahar-deoghar',
    name: 'Trikuta Hills (Trikut Pahar)',
    short_description: 'Three-peaked sacred mountain range offering ropeway rides, cave hermitages, and ridge views.',
    description: 'Trikut Pahar features three distinct rocky summits named after Brahma, Vishnu, and Mahesh. Home to ancient Rishi Dayananda caves, birdwatching trails, and mountain scenery.',
    district: 'Deoghar',
    category: 'adventure',
    latitude: 24.5020,
    longitude: 86.8450,
    cover_image: '/images/destinations/trikut-pahar.jpg',
    gallery: ['/images/destinations/trikut-pahar.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 20,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── East Singhbhum District ─────────────────────────────────────────────────
  {
    id: 'dest-dalma',
    slug: 'dalma-wildlife-sanctuary',
    name: 'Dalma Wildlife Sanctuary',
    short_description: 'Precipitous hilltop forest range famed for wild Indian elephants and panoramic valley lookouts.',
    description: 'Spanning 195 sq km across the Dalma mountain chain, this sanctuary is a major migratory haven for Asian elephants, barking deer, leopards, and giant squirrels.',
    district: 'East Singhbhum',
    category: 'wildlife',
    latitude: 22.8980,
    longitude: 86.2080,
    cover_image: '/images/destinations/dalma-hills.jpg',
    gallery: ['/images/destinations/dalma-hills.jpg'],
    eco_zone: true,
    best_time: 'October to June',
    entry_fee: 40,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-dimna',
    slug: 'dimna-lake',
    name: 'Dimna Lake & Damodar Foothills',
    short_description: 'Scenic reservoir nestled at the base of Dalma Hills with boating and tranquil picnic groves.',
    description: 'Constructed by Tata Steel near Jamshedpur, Dimna Lake is a crystal-clear artificial lake surrounded by undulating green hills, offering watersports and camping.',
    district: 'East Singhbhum',
    category: 'eco',
    latitude: 22.8550,
    longitude: 86.2360,
    cover_image: '/images/destinations/dimna-lake.jpg',
    gallery: ['/images/destinations/dimna-lake.jpg'],
    eco_zone: true,
    best_time: 'November to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── West Singhbhum District ─────────────────────────────────────────────────
  {
    id: 'dest-saranda',
    slug: 'saranda-forest',
    name: 'Saranda Forest (Land of 700 Hills)',
    short_description: 'Asia’s densest Sal forest canopy home to royal elephants, flying squirrels, and tribal trails.',
    description: 'Saranda encompasses 820 sq km of virgin Sal tree wilderness. Revered for its deep canopy where sunlight barely pierces the ground, it is a biodiversity crown jewel of Eastern India.',
    district: 'West Singhbhum',
    category: 'wildlife',
    latitude: 22.3100,
    longitude: 85.3400,
    cover_image: '/images/destinations/saranda-forest.jpg',
    gallery: ['/images/destinations/saranda-forest.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-hirni',
    slug: 'hirni-falls',
    name: 'Hirni Falls',
    short_description: 'Lush 37-metre cascade tucked away in dense forest corridors near Bandgaon.',
    description: 'Formed by the Ramgarha River rushing through rugged forested terrain, Hirni Falls features scenic hanging bridges, viewing decks, and peaceful natural surroundings.',
    district: 'West Singhbhum',
    category: 'waterfall',
    latitude: 22.9500,
    longitude: 85.3800,
    cover_image: '/images/destinations/hirni-falls.jpg',
    gallery: ['/images/destinations/hirni-falls.jpg'],
    eco_zone: true,
    best_time: 'August to February',
    entry_fee: 15,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Saraikela Kharsawan District ────────────────────────────────────────────
  {
    id: 'dest-chandil',
    slug: 'chandil-dam',
    name: 'Chandil Dam & Subarnarekha Reservoir',
    short_description: 'Massive multipurpose lake offering boat cruises, fisheries, and Chhau dance cultural camps.',
    description: 'Built over the Subarnarekha River, Chandil Dam features an expansive 250 sq km water catchment, tourist boating club, and a museum containing 2000-year-old rock inscriptions.',
    district: 'Saraikela Kharsawan',
    category: 'eco',
    latitude: 22.9700,
    longitude: 86.0200,
    cover_image: '/images/destinations/chandil-dam.jpg',
    gallery: ['/images/destinations/chandil-dam.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Khunti District ─────────────────────────────────────────────────────────
  {
    id: 'dest-panchghagh',
    slug: 'panchghagh-falls',
    name: 'Panchghagh Falls',
    short_description: 'Five parallel streaming cascades breaking gently over wide polished rock plateaus.',
    description: 'Formed by the Banai River dividing into five pristine streams, Panchghagh is a safe and serene water park destination popular with families and eco-travelers.',
    district: 'Khunti',
    category: 'waterfall',
    latitude: 22.9900,
    longitude: 85.2400,
    cover_image: '/images/destinations/panchghagh-falls.jpg',
    gallery: ['/images/destinations/panchghagh-falls.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Giridih District ────────────────────────────────────────────────────────
  {
    id: 'dest-parasnath',
    slug: 'parasnath-shikharji',
    name: 'Parasnath Hill (Shikharji)',
    short_description: 'The highest summit in Jharkhand (1,365 m) and most sacred pilgrimage site for Jainism.',
    description: 'Rising sharply above the Chotanagpur Plateau, Shikharji is where twenty of the twenty-four Jain Tirthankaras attained Moksha. Revered mountain trail with breathtaking summit vistas.',
    district: 'Giridih',
    category: 'religious',
    latitude: 23.9600,
    longitude: 86.1300,
    cover_image: '/images/destinations/parasnath-shikharji.jpg',
    gallery: ['/images/destinations/parasnath-shikharji.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-usri',
    slug: 'usri-falls',
    name: 'Usri Falls, Giridih',
    short_description: 'Picturesque gorge waterfall dropping in three stages into an ancient granite canyon.',
    description: 'The Usri River drops 12 metres in three distinct streams through massive boulders of granite, surrounded by dense greenery in the Parasnath foothills.',
    district: 'Giridih',
    category: 'waterfall',
    latitude: 24.1800,
    longitude: 86.3900,
    cover_image: '/images/destinations/usri-falls.jpg',
    gallery: ['/images/destinations/usri-falls.jpg'],
    eco_zone: true,
    best_time: 'August to February',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Dhanbad District ────────────────────────────────────────────────────────
  {
    id: 'dest-maithon',
    slug: 'maithon-dam',
    name: 'Maithon Dam (Lake of Flowers)',
    short_description: 'Sprawling 65 sq km blue reservoir on Barakar River with speedboating and deer park islands.',
    description: 'Maithon (Mai-ka-than) is famous for its underground hydel power station, island sanctuaries, and the revered 500-year-old Kalyaneshwari temple.',
    district: 'Dhanbad',
    category: 'eco',
    latitude: 23.7800,
    longitude: 86.8100,
    cover_image: '/images/destinations/maithon-dam.jpg',
    gallery: ['/images/destinations/maithon-dam.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Dumka District ──────────────────────────────────────────────────────────
  {
    id: 'dest-basukinath',
    slug: 'basukinath-dham',
    name: 'Basukinath Shiva Dham',
    short_description: 'Renowned Shiva shrine where pilgrims conclude their sacred Kanwar Yatra from Deoghar.',
    description: 'Basukinath is considered the court of Lord Shiva where devotees pray after offering holy Ganga water at Baidyanath Jyotirlinga. Rich in spiritual traditions and fairs.',
    district: 'Dumka',
    category: 'religious',
    latitude: 24.3800,
    longitude: 86.8900,
    cover_image: '/images/destinations/basukinath-dham.jpg',
    gallery: ['/images/destinations/basukinath-dham.jpg'],
    eco_zone: false,
    best_time: 'All year',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-massanjore',
    slug: 'massanjore-dam',
    name: 'Massanjore Dam (Canada Dam)',
    short_description: 'Picturesque dam across Mayurakshi River framed by emerald Chotanagpur hill ranges.',
    description: 'Constructed in 1955 with Canadian assistance, Massanjore Dam forms a breathtaking 67 sq km lake surrounded by hills and tribal villages, offering water leisure and resorts.',
    district: 'Dumka',
    category: 'eco',
    latitude: 24.1100,
    longitude: 87.3200,
    cover_image: '/images/destinations/massanjore-dam.jpg',
    gallery: ['/images/destinations/massanjore-dam.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Gumla District ──────────────────────────────────────────────────────────
  {
    id: 'dest-anjan-dham',
    slug: 'anjan-dham-gumla',
    name: 'Anjan Dham (Hanuman Birthplace)',
    short_description: 'Mythological birthplace of Lord Hanuman featuring ancient cave shrines and hilltop vistas.',
    description: 'Anjan Dham is situated inside dense forests 21 km from Gumla town. Legend says Mother Anjana worshipped Lord Shiva here and gave birth to Hanuman inside the Chakra cave.',
    district: 'Gumla',
    category: 'religious',
    latitude: 23.1200,
    longitude: 84.5200,
    cover_image: '/images/destinations/anjan-dham.jpg',
    gallery: ['/images/destinations/anjan-dham.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-navratangarh',
    slug: 'navratangarh-fort',
    name: 'Navratangarh Fort (Sisai)',
    short_description: 'UNESCO Tentative List 16th-century fortress palace of the Nagvanshi tribal kings.',
    description: 'Built by Nagvanshi King Durjan Sal in the 16th century, Navratangarh features a nine-storied royal palace, underground vaults, treasure wells, and Kapilnath Shiva temple.',
    district: 'Gumla',
    category: 'heritage',
    latitude: 23.1800,
    longitude: 84.9700,
    cover_image: '/images/destinations/navratangarh-fort.jpg',
    gallery: ['/images/destinations/navratangarh-fort.jpg'],
    eco_zone: false,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Sahibganj District ──────────────────────────────────────────────────────
  {
    id: 'dest-rajmahal',
    slug: 'rajmahal-fossil-park',
    name: 'Rajmahal Hills & Jurassic Fossil Park',
    short_description: 'Rare 140-million-year-old Jurassic plant fossils overlooking the sacred Ganga River bend.',
    description: 'The Rajmahal Hills preserve plant fossils from the Upper Gondwana Jurassic era (140-116 million years ago), offering international geological significance and panoramic river views.',
    district: 'Sahibganj',
    category: 'heritage',
    latitude: 25.0500,
    longitude: 87.8400,
    cover_image: '/images/destinations/rajmahal-fossils.jpg',
    gallery: ['/images/destinations/rajmahal-fossils.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 20,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-udhwa',
    slug: 'udhwa-lake-bird-sanctuary',
    name: 'Udhwa Lake Bird Sanctuary',
    short_description: 'Jharkhand’s only bird sanctuary, hosting migratory Siberian ducks and kingfishers on the Ganga.',
    description: 'Sprawled across Pataura and Berhale natural wetlands along the Ganga River, Udhwa sanctuary shelters over 100 species of migratory and resident birds during winter.',
    district: 'Sahibganj',
    category: 'wildlife',
    latitude: 24.9700,
    longitude: 87.8200,
    cover_image: '/images/destinations/udhwa-bird-sanctuary.jpg',
    gallery: ['/images/destinations/udhwa-bird-sanctuary.jpg'],
    eco_zone: true,
    best_time: 'November to February',
    entry_fee: 30,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Hazaribagh District ─────────────────────────────────────────────────────
  {
    id: 'dest-hazaribagh-np',
    slug: 'hazaribagh-national-park',
    name: 'Hazaribagh National Park',
    short_description: 'Picturesque wildlife reserve with watchtowers overlooking Sal woodlands and Cheetal deer.',
    description: 'Established in 1955 across 184 sq km of pristine Chotanagpur terrain, this park features watchtowers, waterholes frequented by leopards and sambar deer, and ancient nature trails.',
    district: 'Hazaribagh',
    category: 'wildlife',
    latitude: 24.0800,
    longitude: 85.3600,
    cover_image: '/images/destinations/hazaribagh-national-park.jpg',
    gallery: ['/images/destinations/hazaribagh-national-park.jpg'],
    eco_zone: true,
    best_time: 'October to April',
    entry_fee: 30,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-canary-hill',
    slug: 'canary-hill-hazaribagh',
    name: 'Canary Hill & Forest Watchtower',
    short_description: 'Hilltop viewpoint offering 360-degree vistas of Hazaribagh town and dense Sal forests.',
    description: 'Surrounded by pine groves and rock formations, Canary Hill has a colonial-style rest house and observation tower providing sweeping sunset views across the plateau.',
    district: 'Hazaribagh',
    category: 'eco',
    latitude: 24.0200,
    longitude: 85.3700,
    cover_image: '/images/destinations/canary-hill.jpg',
    gallery: ['/images/destinations/canary-hill.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Chatra District ─────────────────────────────────────────────────────────
  {
    id: 'dest-bhadrakali',
    slug: 'bhadrakali-temple-itkhori',
    name: 'Bhadrakali Temple Complex, Itkhori',
    short_description: 'Unique tri-religious pilgrimage center uniting Hindu, Buddhist, and Jain sacred traditions.',
    description: 'Located at the sangam of Mohane and Mahane rivers, Itkhori features a 9th-century idol of Goddess Bhadrakali, a Buddhist stupa with 1,004 miniature carvings, and Jain Tirthankara relics.',
    district: 'Chatra',
    category: 'heritage',
    latitude: 24.2900,
    longitude: 85.1600,
    cover_image: '/images/destinations/itkhori-bhadrakali.jpg',
    gallery: ['/images/destinations/itkhori-bhadrakali.jpg'],
    eco_zone: false,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Simdega District ────────────────────────────────────────────────────────
  {
    id: 'dest-kelaghagh',
    slug: 'kelaghagh-dam',
    name: 'Kelaghagh Dam & Falls',
    short_description: 'Scenic dam on the Chhinda River nestled between rugged hills with lakeside gardens.',
    description: 'Surrounded by picturesque hillocks, Kelaghagh Dam is the pride of Simdega, offering boating, natural cascading waterfalls, and eco-parks for visitors.',
    district: 'Simdega',
    category: 'waterfall',
    latitude: 22.6100,
    longitude: 84.5000,
    cover_image: '/images/destinations/kelaghagh-dam.jpg',
    gallery: ['/images/destinations/kelaghagh-dam.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Koderma District ────────────────────────────────────────────────────────
  {
    id: 'dest-tilaiya',
    slug: 'tilaiya-dam',
    name: 'Tilaiya Dam & Reservoir',
    short_description: 'First dam of DVC across Barakar River with scenic boating and Urwan eco-resort complex.',
    description: 'Surrounded by forested hill ranges, Tilaiya Dam provides expansive water views, reservoir island boating, and waterfront parks along the Grand Trunk road corridor.',
    district: 'Koderma',
    category: 'eco',
    latitude: 24.3200,
    longitude: 85.5200,
    cover_image: '/images/destinations/tilaiya-dam.jpg',
    gallery: ['/images/destinations/tilaiya-dam.jpg'],
    eco_zone: true,
    best_time: 'October to March',
    entry_fee: 15,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },

  // ── Newly Added Verified Heritage & Cultural Destinations ───────────────────
  {
    id: 'dest-pahari-mandir',
    slug: 'pahari-mandir-ranchi',
    name: 'Pahari Mandir, Ranchi',
    short_description: '300-foot hilltop Shiva Temple offering breathtaking 360-degree panoramic views of Ranchi city.',
    description: 'Pahari Mandir is situated atop Ranchi Hill (Phari). Dedicated to Lord Shiva (Pahario Baba), pilgrims climb 468 stone steps to reach the sanctum. It also holds unique historical pride where the Indian Tricolour is hoisted on Independence and Republic Days.',
    district: 'Ranchi',
    category: 'religious',
    latitude: 23.3700,
    longitude: 85.3150,
    cover_image: '/images/destinations/pahari-mandir.jpg',
    gallery: ['/images/destinations/pahari-mandir.jpg', '/images/destinations/ranchi-city.jpg'],
    eco_zone: false,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-mccluskieganj',
    slug: 'mccluskieganj-heritage',
    name: 'McCluskieganj Heritage Town',
    short_description: 'Historic colonial village founded by the Colonisation Society of India with quaint stone bungalows.',
    description: 'Established in 1933 by Timothy McCluskie, this European-style settlement in Ranchi district is famous for colonial architecture, quaint English bungalows, the Don Bosco Academy, and serene forest walks.',
    district: 'Ranchi',
    category: 'heritage',
    latitude: 23.6550,
    longitude: 85.0080,
    cover_image: '/images/destinations/mccluskieganj.jpg',
    gallery: ['/images/destinations/mccluskieganj.jpg'],
    eco_zone: false,
    best_time: 'October to February',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-tagore-hill',
    slug: 'tagore-hill-ranchi',
    name: 'Tagore Hill (Morabadi)',
    short_description: 'Historic hilltop ashram and scenic pavilion where Jyotirindranath Tagore composed literary works.',
    description: 'Standing at a height of 300 feet in Morabadi, Ranchi, Tagore Hill is dedicated to the artistic legacy of the Tagore family. The Brahma Mandir pavilion on top offers sweeping sunset vistas over Ranchi.',
    district: 'Ranchi',
    category: 'heritage',
    latitude: 23.4010,
    longitude: 85.3370,
    cover_image: '/images/destinations/tagore-hill.jpg',
    gallery: ['/images/destinations/tagore-hill.jpg', '/images/destinations/ranchi-city.jpg'],
    eco_zone: false,
    best_time: 'Year round',
    entry_fee: 20,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-maluti',
    slug: 'maluti-terracotta-temples',
    name: 'Maluti Terracotta Temples',
    short_description: 'A remarkable heritage cluster of 108 historic terracotta temples depicting Ramayana epics in Dumka.',
    description: 'Constructed between the 17th and 19th centuries by the Nankar royal dynasty of Dumka, Maluti is known as the village of temples. The intricate terracotta panels depict mythological battle scenes and regional folk motifs.',
    district: 'Dumka',
    category: 'heritage',
    latitude: 24.1600,
    longitude: 87.6800,
    cover_image: '/images/destinations/maluti-temples.jpg',
    gallery: ['/images/destinations/maluti-temples.jpg'],
    eco_zone: false,
    best_time: 'October to March',
    entry_fee: 0,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dest-surajkund',
    slug: 'surajkund-hot-springs',
    name: 'Surajkund Hot Springs',
    short_description: 'The hottest natural sulphur spring in India (88°C) surrounded by therapeutic mineral pools in Hazaribagh.',
    description: 'Located in Belkapi near Barhi, Surajkund features five natural thermal kunds (Suraj, Ram, Lakshman, Sita, and Bharat). The sulphur-rich steaming waters are renowned for curative properties.',
    district: 'Hazaribagh',
    category: 'eco',
    latitude: 24.1500,
    longitude: 85.6400,
    cover_image: '/images/destinations/surajkund.jpg',
    gallery: ['/images/destinations/surajkund.jpg'],
    eco_zone: true,
    best_time: 'November to February',
    entry_fee: 10,
    status: 'published',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];
