/**
 * Curated Marketplace Products & Experiences Data for Jharkhand Diaries
 *
 * Distinct from Accommodations:
 * - Products: Handcrafted art, GI Sohrai canvas, Dokra figurines, Bamboo lamps, Kuchai Tussar Silk stoles, Organic Wild Honey.
 * - Experiences: Sohrai Masterclass, Dokra Lost-Wax Workshop, Tribal Cooking Master, Reservoir Kayaking, Elephant Sanctuary Trail.
 *
 * Conforms to ProviderOffering type for full compatibility with Supabase.
 */

import type { ProviderOffering } from '../types/provider';

export interface MarketplaceItem extends ProviderOffering {
  materials?: string;
  artisan_name?: string;
  craft_tradition?: string;
  dimensions?: string;
  duration?: string;
  rating?: number;
  reviewsCount?: number;
  stock?: number;
  gi_tagged?: boolean;
}

export const JHARKHAND_MARKETPLACE_PRODUCTS: MarketplaceItem[] = [
  {
    id: 'prod-sohrai-canvas',
    provider_id: '00000000-0000-0000-0000-000000000010',
    kind: 'product',
    name: 'GI Sohrai Tree of Life Painted Canvas',
    slug: 'gi-sohrai-tree-of-life-canvas',
    short_description:
      'Handmade mud & earth pigment canvas depicting the sacred Tree of Life and forest deer by master Santali women artisans.',
    description:
      'An authentic GI-certified Sohrai wall art interpretation created on archival handmade cotton canvas using four sacred earth clays: Dhudhi (white kaolin), Lalmati (red haematite), Charak (black manganese), and Pili mati (yellow ochre). Painted with chewed date-palm twigs according to generational motifs.',
    category: 'Handicrafts & Art',
    district: 'Hazaribagh',
    address: 'Bhadal Village Artisan Guild, Hazaribagh',
    price: 2400,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/products/sohrai-canvas.jpg',
    gallery: [
      '/images/products/sohrai-canvas.jpg',
      '/images/art/sohrai-painting.jpg',
    ],
    metadata: {
      craft_tradition: 'Sohrai Wall Painting',
      artisan_name: 'Parvati Devi (National Awardee)',
      materials: 'Natural Earth Pigments on Handmade Khadi Canvas',
      dimensions: '24 x 36 inches',
      gi_tagged: true,
      stock: 6,
      rating: 5.0,
      reviewsCount: 19,
    },
    materials: 'Natural Earth Pigments on Handmade Khadi Canvas',
    artisan_name: 'Parvati Devi (National Awardee)',
    craft_tradition: 'Sohrai Wall Painting',
    dimensions: '24 x 36 inches',
    gi_tagged: true,
    stock: 6,
    rating: 5.0,
    reviewsCount: 19,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-dokra-musicians',
    provider_id: '00000000-0000-0000-0000-000000000011',
    kind: 'product',
    name: 'Dokra Lost-Wax Bell Metal Musician Trio',
    slug: 'dokra-lost-wax-musician-trio',
    short_description:
      '4,000-year-old lost-wax bronze casting of traditional Mandar, Nagara and Flute tribal musicians.',
    description:
      'Handcrafted using the ancient non-ferrous lost-wax metal casting technique by Malhor artisans. Beeswax cords are intricately hand-coiled over river clay cores before molten brass is poured. Each sculpture is unique as the clay mould is destroyed during retrieval.',
    category: 'Handicrafts & Art',
    district: 'Khunti',
    address: 'Torpa Dhokra Metal Craft Cluster, Khunti',
    price: 1850,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/products/dokra-figurine.jpg',
    gallery: [
      '/images/products/dokra-figurine.jpg',
      '/images/art/dokra-craft.jpg',
    ],
    metadata: {
      craft_tradition: 'Dhokra Lost-Wax Casting',
      artisan_name: 'Budheshwar Karmakar',
      materials: 'Recycled Bell Metal & Brass',
      dimensions: '8 inches height (Set of 3)',
      gi_tagged: false,
      stock: 12,
      rating: 4.9,
      reviewsCount: 27,
    },
    materials: 'Recycled Bell Metal & Brass',
    artisan_name: 'Budheshwar Karmakar',
    craft_tradition: 'Dhokra Lost-Wax Casting',
    dimensions: '8 inches height (Set of 3)',
    gi_tagged: false,
    stock: 12,
    rating: 4.9,
    reviewsCount: 27,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-bamboo-lantern',
    provider_id: '00000000-0000-0000-0000-000000000012',
    kind: 'product',
    name: 'Woven Forest Bamboo Ambient Lantern',
    slug: 'woven-forest-bamboo-ambient-lantern',
    short_description:
      'Geometric woven bamboo pendant lampshade crafted from seasoned green Sal forest reeds.',
    description:
      'Hand-split and hand-woven by Mahli tribal craftsmen using mature green bamboo harvested from the forests of Simdega. Casts warm geometric shadow patterns and is treated with natural neem oil for insect and moisture resistance.',
    category: 'Home Decor',
    district: 'Simdega',
    address: 'Kolebira Bamboo Craft Cooperative, Simdega',
    price: 950,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/products/bamboo-lamp.jpg',
    gallery: [
      '/images/products/bamboo-lamp.jpg',
      '/images/art/bamboo-craft.jpg',
    ],
    metadata: {
      craft_tradition: 'Mahli Bamboo Weaving',
      artisan_name: 'Mahli Weavers Self-Help Group',
      materials: '100% Sustainable Green Forest Bamboo',
      dimensions: '12 x 14 inches',
      gi_tagged: false,
      stock: 25,
      rating: 4.8,
      reviewsCount: 14,
    },
    materials: '100% Sustainable Green Forest Bamboo',
    artisan_name: 'Mahli Weavers Self-Help Group',
    craft_tradition: 'Mahli Bamboo Weaving',
    dimensions: '12 x 14 inches',
    gi_tagged: false,
    stock: 25,
    rating: 4.8,
    reviewsCount: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-tussar-silk-stole',
    provider_id: '00000000-0000-0000-0000-000000000013',
    kind: 'product',
    name: 'Kuchai Organic Wild Tussar Silk Stole',
    slug: 'kuchai-organic-wild-tussar-silk-stole',
    short_description:
      'Pure handloom wild Tussar silk stole with natural golden sheen and tribal temple border motifs.',
    description:
      'Certified organic Ahimsa Tussar silk cultivated in the Sal & Asan forests of Saraikela Kharsawan. Reeled by tribal women and handwoven on pit looms with natural textured slubs and herbal dyed borders.',
    category: 'Textiles',
    district: 'Saraikela Kharsawan',
    address: 'Kuchai Silk Weavers Apex Federation',
    price: 3200,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/products/tussar-stole.jpg',
    gallery: [
      '/images/products/tussar-stole.jpg',
      '/images/art/tussar-silk.jpg',
    ],
    metadata: {
      craft_tradition: 'Kuchai Silk Handloom',
      artisan_name: 'Kharsawan Handloom Guild',
      materials: '100% Organic Wild Tussar Silk',
      dimensions: '22 x 78 inches',
      gi_tagged: true,
      stock: 8,
      rating: 5.0,
      reviewsCount: 32,
    },
    materials: '100% Organic Wild Tussar Silk',
    artisan_name: 'Kharsawan Handloom Guild',
    craft_tradition: 'Kuchai Silk Handloom',
    dimensions: '22 x 78 inches',
    gi_tagged: true,
    stock: 8,
    rating: 5.0,
    reviewsCount: 32,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-wild-sal-honey',
    provider_id: '00000000-0000-0000-0000-000000000014',
    kind: 'product',
    name: 'Raw Wild Sal Forest Blossom Honey',
    slug: 'raw-wild-sal-forest-honey',
    short_description:
      'Unprocessed forest honey sustainably gathered from wild rock bees (Apis dorsata) in Saranda.',
    description:
      'Pure raw honey extracted by Ho tribal honey collectors from deep within the pristine Sal canopy of Saranda. Unpasteurized and unfiltered, retaining natural bee pollen, enzymes, and a distinct floral herbal aroma.',
    category: 'Local Food & Forest Goods',
    district: 'West Singhbhum',
    address: 'Saranda Forest Honey Collectors Society',
    price: 650,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/products/wild-honey.jpg',
    gallery: [
      '/images/products/wild-honey.jpg',
    ],
    metadata: {
      craft_tradition: 'Wild Forest Foraging',
      artisan_name: 'Ho Indigenous Collectors Cooperative',
      materials: '100% Pure Raw Forest Honey',
      dimensions: '500g Glass Jar',
      gi_tagged: false,
      stock: 40,
      rating: 4.9,
      reviewsCount: 45,
    },
    materials: '100% Pure Raw Forest Honey',
    artisan_name: 'Ho Indigenous Collectors Cooperative',
    craft_tradition: 'Wild Forest Foraging',
    dimensions: '500g Glass Jar',
    gi_tagged: false,
    stock: 40,
    rating: 4.9,
    reviewsCount: 45,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const JHARKHAND_MARKETPLACE_EXPERIENCES: MarketplaceItem[] = [
  {
    id: 'exp-sohrai-masterclass',
    provider_id: '00000000-0000-0000-0000-000000000020',
    kind: 'experience',
    name: 'Sohrai & Khovar Painting Masterclass with Guild Women',
    slug: 'sohrai-painting-masterclass',
    short_description:
      'Learn ancient comb-cutting and natural clay pigment techniques directly from generational mural masters on handmade tiles.',
    description:
      'A 3.5-hour hands-on cultural workshop in a traditional Hazaribagh village courtyard. Prepare natural earth pigments (red, black, white), learn comb-incising motifs, and paint your own souvenir terracotta tile guided by master women artists.',
    category: 'Workshops',
    district: 'Hazaribagh',
    address: 'Bhadal Heritage Art Village, Hazaribagh',
    price: 750,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/experiences/sohrai-workshop.jpg',
    gallery: [
      '/images/experiences/sohrai-workshop.jpg',
      '/images/art/sohrai-painting.jpg',
    ],
    metadata: {
      host_name: 'Women Artisans Guild',
      duration: '3.5 Hours',
      highlights: ['All clay & canvas materials provided', 'Take home painted tile', 'Herbal welcome tea & Dhuska'],
      rating: 4.9,
      reviewsCount: 22,
    },
    duration: '3.5 Hours',
    artisan_name: 'Women Artisans Guild',
    rating: 4.9,
    reviewsCount: 22,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exp-dokra-studio-tour',
    provider_id: '00000000-0000-0000-0000-000000000021',
    kind: 'experience',
    name: 'Dokra Lost-Wax Bell Metal Casting Studio Workshop',
    slug: 'dokra-lost-wax-casting-workshop',
    short_description:
      'Witness the 4,000-year-old lost-wax molten brass process and sculpt your own beeswax figurine.',
    description:
      'Step inside an active metallurgy foundry in Khunti. Learn wax thread extrusion, clay core preparation, charcoal furnace firing, and pour your own bronze miniature token.',
    category: 'Workshops',
    district: 'Khunti',
    address: 'Torpa Artisan Metallurgy Studio, Khunti',
    price: 850,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/art/dokra-craft.jpg',
    gallery: [
      '/images/art/dokra-craft.jpg',
      '/images/products/dokra-figurine.jpg',
    ],
    metadata: {
      host_name: 'Master Dhokra Brassmiths',
      duration: '3 Hours',
      highlights: ['Studio tour & demo', 'Wax model making session', 'Souvenir bronze figurine'],
      rating: 4.8,
      reviewsCount: 16,
    },
    duration: '3 Hours',
    artisan_name: 'Master Dhokra Brassmiths',
    rating: 4.8,
    reviewsCount: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exp-tribal-cooking-class',
    provider_id: '00000000-0000-0000-0000-000000000022',
    kind: 'experience',
    name: 'Tribal Foraging, Dheki Pounding & Cooking Masterclass',
    slug: 'tribal-cooking-masterclass',
    short_description:
      'Forage wild forest herbs, pound rice flour on ancestral Dheki, and slow-cook Dhuska & Rugra in earthenware.',
    description:
      'An immersive 4-hour culinary journey in a village kitchen on the fringe of Saranda Forest. Gather edible greens, learn clay-pot steaming of Chilka Roti, and enjoy a sit-down meal served on Sal leaf patra.',
    category: 'Culinary Experiences',
    district: 'West Singhbhum',
    address: 'Manoharpur Tribal Hearth Kitchen, West Singhbhum',
    price: 1100,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/experiences/tribal-cooking.jpg',
    gallery: [
      '/images/experiences/tribal-cooking.jpg',
      '/images/cuisine/dhuska.jpg',
    ],
    metadata: {
      host_name: 'Santhali Hearth Collective',
      duration: '4 Hours',
      highlights: ['Full traditional 5-course meal', 'Recipe booklet', 'Organic wild ingredients'],
      rating: 4.9,
      reviewsCount: 31,
    },
    duration: '4 Hours',
    artisan_name: 'Santhali Hearth Collective',
    rating: 4.9,
    reviewsCount: 31,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'exp-patratu-kayaking',
    provider_id: '00000000-0000-0000-0000-000000000023',
    kind: 'experience',
    name: 'Patratu Reservoir Kayaking & Sunset Sail',
    slug: 'patratu-kayaking-sunset-sail',
    short_description:
      'Glide across emerald waters framed by serpentine mountain ghats with safety instruction and sunset photos.',
    description:
      'Paddle along the tranquil inlets of Patratu Dam at the base of lush green valley slopes. Guided by certified water sports trainers with high-end single and tandem kayaks and life jackets included.',
    category: 'Adventure',
    district: 'Ramgarh',
    address: 'Patratu Water Sports Complex, Ramgarh',
    price: 950,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/experiences/lake-kayaking.jpg',
    gallery: [
      '/images/experiences/lake-kayaking.jpg',
      '/images/destinations/patratu-valley.jpg',
    ],
    metadata: {
      host_name: 'Jharkhand Water Sports Club',
      duration: '2 Hours',
      highlights: ['Certified instructor assistance', 'High-res digital photos', 'Safety life jackets'],
      rating: 4.8,
      reviewsCount: 39,
    },
    duration: '2 Hours',
    artisan_name: 'Jharkhand Water Sports Club',
    rating: 4.8,
    reviewsCount: 39,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const JHARKHAND_CURATED_TOURS: ProviderOffering[] = [
  {
    id: 'tour-hazaribagh-heritage',
    provider_id: '00000000-0000-0000-0000-000000000020',
    kind: 'tour',
    name: 'Hazaribagh Heritage & Tribal Culture Walk',
    slug: 'hazaribagh-heritage-tribal-culture-walk',
    short_description:
      'A 6-hour guided circuit through Bhadal village, Sohrai mural ateliers, Santali craft guilds, and ancient forest shrines with a certified local historian.',
    description:
      'Begin your morning with a ceremonial welcome at the Santali Akhra (community ground). Walk through winding lanes lined with living Sohrai murals still painted by master women artisans. Visit a working Dokra lost-wax foundry, witness bamboo mat weaving, and conclude at the hilltop tribal deity shrine with panoramic views. Includes organic lunch at a SHG kitchen and take-home painted tile.',
    category: 'Heritage & Culture',
    district: 'Hazaribagh',
    address: 'Bhadal Village, Hazaribagh, Jharkhand',
    price: 1200,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/hazaribagh.jpg',
    gallery: ['/images/destinations/hazaribagh.jpg'],
    metadata: {
      guide_name: 'Ratan Murmu (Certified Heritage Guide)',
      duration: '6 Hours',
      max_participants: 10,
      specialties: ['Tribal Art', 'Sohrai Painting', 'Local History'],
      languages: ['Hindi', 'Santali', 'English'],
      includes: ['Organic lunch', 'Craft workshop', 'Take-home tile'],
      rating: 4.9,
      reviews_count: 28,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tour-netarhat-pine-trek',
    provider_id: '00000000-0000-0000-0000-000000000020',
    kind: 'tour',
    name: 'Netarhat Sunrise Pine Forest Trek & Stargazing',
    slug: 'netarhat-sunrise-pine-trek-stargazing',
    short_description:
      'Two-day high-altitude trek through Jharkhand\'s "Queen of Chotanagpur" ridge with campfire tribal stories and certified dark-sky stargazing at 3,600 ft.',
    description:
      'Ascend through Jharkhand\'s most iconic pine and sal forest belt at dawn. Your expert guide navigates ancient tribal trails through Koel river gorge viewpoints, colonial-era sunset point, and the remote Lodhung waterfall. Night camp under a sky unpolluted by light, with hot locally prepared meals and folk music around the fire.',
    category: 'Wildlife & Nature',
    district: 'Latehar',
    address: 'Netarhat Pine Ridge, Latehar District',
    price: 2800,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/netarhat.jpg',
    gallery: ['/images/destinations/netarhat.jpg'],
    metadata: {
      guide_name: 'Latehar Eco-Guides Collective',
      duration: '2 Days / 1 Night',
      max_participants: 8,
      specialties: ['Nature', 'Photography', 'Adventure'],
      languages: ['Hindi', 'Nagpuri', 'English'],
      includes: ['Camp accommodation', 'All meals', 'Torchlight & gear'],
      rating: 5.0,
      reviews_count: 41,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tour-dalma-wildlife',
    provider_id: '00000000-0000-0000-0000-000000000021',
    kind: 'tour',
    name: 'Dalma Wildlife Sanctuary Deep Forest Trail',
    slug: 'dalma-wildlife-deep-forest-trail',
    short_description:
      'A 5-hour guided safari through elephant and leopard corridors of Dalma Hills with Forest Department-certified naturalists.',
    description:
      'Join a Forest Department certified guide for an immersive wildlife walk through Dalma Wildlife Sanctuary. Spot wild elephants, leopards, sambar deer, and 200+ bird species. Your guide explains ecological conservation, tribal forest rights, and tracks animal paths. Includes binoculars, safari shirt, and post-trail naturalist debrief.',
    category: 'Wildlife & Nature',
    district: 'Purbi Singhbhum',
    address: 'Dalma Hills Forest Gate, Jamshedpur',
    price: 1800,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/dassam-falls.jpg',
    gallery: ['/images/destinations/dassam-falls.jpg'],
    metadata: {
      guide_name: 'Forest Dept. Certified Naturalists',
      duration: '5 Hours',
      max_participants: 12,
      specialties: ['Wildlife', 'Photography', 'Conservation'],
      languages: ['Hindi', 'Bengali', 'English'],
      includes: ['Forest permit', 'Binoculars', 'Jungle snack pack'],
      rating: 4.9,
      reviews_count: 56,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'tour-rajrappa-pilgrimage',
    provider_id: '00000000-0000-0000-0000-000000000021',
    kind: 'tour',
    name: 'Rajrappa Chhinnamasta Pilgrimage & Damodar River Walk',
    slug: 'rajrappa-chhinnamasta-pilgrimage-damodar',
    short_description:
      'A half-day spiritual circuit combining the sacred Chhinnamasta temple, Damodar-Bhairavi river confluence, and ancient Shakta traditions with a local priest guide.',
    description:
      'Experience the living spiritual heart of Jharkhand at Rajrappa, one of India\'s most powerful Shakta shrines at the dramatic confluence of the Damodar and Bhairavi rivers. Your guide is a trained pandit who explains temple iconography, tribal Devi traditions, sacred river lore, and seasonal pilgrimage patterns. After darshan, explore cliff-side orchid gardens and riverside rock paintings.',
    category: 'Pilgrimage',
    district: 'Ramgarh',
    address: 'Rajrappa Temple Complex, Ramgarh',
    price: 800,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/rajrappa.jpg',
    gallery: ['/images/destinations/rajrappa.jpg'],
    metadata: {
      guide_name: 'Pt. Vijay Kumar Sharma',
      duration: '4 Hours',
      max_participants: 15,
      specialties: ['Pilgrimage', 'Heritage', 'Local History'],
      languages: ['Hindi', 'Khortha', 'Bengali'],
      includes: ['Temple prasad', 'River boat ride', 'Audio storytelling'],
      rating: 4.8,
      reviews_count: 72,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const JHARKHAND_CURATED_TRANSPORT: ProviderOffering[] = [
  {
    id: 'transport-ranchi-suv',
    provider_id: '00000000-0000-0000-0000-000000000030',
    kind: 'transport',
    name: 'Ranchi Full-Day Sightseeing SUV (7-Seater)',
    slug: 'ranchi-full-day-sightseeing-suv',
    short_description:
      'Comfortable 7-seat AC Innova for full-day Ranchi city sightseeing covering Hundru Falls, Rock Garden, Sun Temple, and Patratu Valley.',
    description:
      'Start your Ranchi exploration in total comfort. Our fleet of air-conditioned 7-seater Toyota Innova vehicles is managed by professional, licensed drivers who also serve as knowledgeable local guides. The standard Ranchi circuit covers Hundru Falls, Jonha Falls, Rock Garden, Tagore Hill, Birsa Zoological Park, and Patratu Valley Loop — adjustable to your schedule.',
    category: 'Sightseeing Tour',
    district: 'Ranchi',
    address: 'Ranchi City, Jharkhand',
    price: 3500,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/ranchi-skyline.jpg',
    gallery: ['/images/destinations/ranchi-skyline.jpg'],
    metadata: {
      operator_name: 'Jharkhand Travels & Tourism',
      vehicle_type: 'Toyota Innova (SUV)',
      seating_capacity: 7,
      ac_available: true,
      features: ['Professional Driver', 'Flexible Route', 'Fuel Included', 'Water Bottles'],
      rating: 4.8,
      reviews_count: 88,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'transport-netarhat-expedition',
    provider_id: '00000000-0000-0000-0000-000000000030',
    kind: 'transport',
    name: 'Ranchi to Netarhat 4x4 Expedition Vehicle',
    slug: 'ranchi-netarhat-4x4-expedition',
    short_description:
      'Rugged 4x4 off-road vehicle for the Ranchi–Netarhat–Mahuadanr circuit across jungle roads and forest reserve passes.',
    description:
      'The Ranchi to Netarhat mountain road passes through dense Saranda and Chotanagpur forest belts, river fords, and steep switchbacks only navigable in a proper 4x4 vehicle. Our Mahindra Thar/Bolero fleet is maintained for extreme terrain with experienced off-road drivers who know tribal forest trails, picnic spots, and hidden waterfalls along the route.',
    category: 'Outstation',
    district: 'Latehar',
    address: 'Pickup from Ranchi | Drop at Netarhat',
    price: 5200,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/netarhat.jpg',
    gallery: ['/images/destinations/netarhat.jpg'],
    metadata: {
      operator_name: 'Wild Jharkhand Expeditions',
      vehicle_type: 'Mahindra 4x4 Off-Road',
      seating_capacity: 6,
      ac_available: false,
      features: ['Off-road Capable', 'Emergency Equipment', 'Experienced Driver', 'Route Flexibility'],
      rating: 4.9,
      reviews_count: 34,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'transport-jamshedpur-airport',
    provider_id: '00000000-0000-0000-0000-000000000031',
    kind: 'transport',
    name: 'Sonari Airport Pickup & Drop (Jamshedpur)',
    slug: 'sonari-airport-pickup-drop-jamshedpur',
    short_description:
      'Reliable, punctual AC sedan airport transfer service from Sonari Airport to any Jamshedpur hotel, home, or tourist site.',
    description:
      'Stress-free arrival and departure transfers at Jamshedpur\'s Sonari Airport. Our drivers monitor flight timings to ensure on-time pickup. Vehicles include AC sedans (4 pax) and SUVs (7 pax). Hotel and resort partnerships available for direct billing. Late night and early morning flights covered 24/7.',
    category: 'Airport Transfer',
    district: 'Purbi Singhbhum',
    address: 'Sonari Airport, Jamshedpur',
    price: 1200,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/rajrappa.jpg',
    gallery: [],
    metadata: {
      operator_name: 'Steel City Transfers',
      vehicle_type: 'AC Sedan / SUV',
      seating_capacity: 4,
      ac_available: true,
      features: ['Flight Tracking', '24/7 Service', 'Meet & Greet', 'Luggage Assistance'],
      rating: 4.7,
      reviews_count: 112,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'transport-saranda-safari',
    provider_id: '00000000-0000-0000-0000-000000000031',
    kind: 'transport',
    name: 'Saranda Forest Safari Jeep (Group — 12 Seater)',
    slug: 'saranda-forest-safari-jeep-group',
    short_description:
      'Open-top safari jeep for group forest journeys through Saranda, Asia\'s largest sal forest, with local naturalist guides.',
    description:
      'Saranda (Sanskrit: "seven hundred hills") is Asia\'s largest sal forest, home to wild elephants, leopards, sloth bears, and 300+ bird species. Our open-top safari jeeps accommodate groups up to 12, with bench seating, roof racks for photography, and a naturalist co-pilot. Ideal for group birdwatching trips, school expeditions, or eco-tourism circuits.',
    category: 'Safari Vehicle',
    district: 'West Singhbhum',
    address: 'Saranda Forest Range, Chaibasa, West Singhbhum',
    price: 4800,
    currency: 'INR',
    status: 'published',
    cover_image: '/images/destinations/dassam-falls.jpg',
    gallery: [],
    metadata: {
      operator_name: 'Saranda Eco-Safari Club',
      vehicle_type: 'Open Safari Jeep',
      seating_capacity: 12,
      ac_available: false,
      features: ['Naturalist Co-pilot', 'Binoculars Provided', 'Open-Top Photography', 'Group Pricing'],
      rating: 4.8,
      reviews_count: 47,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

