-- Demo seed data only.
-- Coordinates, entry fees, and imagery are approximate placeholders for development and UI testing.

insert into public.destinations (
  name,
  slug,
  short_description,
  description,
  district,
  category,
  latitude,
  longitude,
  cover_image,
  gallery,
  eco_zone,
  best_time,
  entry_fee,
  status
) values
  (
    'Hundru Falls',
    'hundru-falls',
    'One of Jharkhand''s most iconic waterfalls, set in a scenic natural landscape.',
    'Hundru Falls is a well-known waterfall destination near Ranchi and is included here as demo seed data for the tourism platform.',
    'Ranchi',
    'waterfall',
    23.3174,
    85.5297,
    'https://placehold.co/1200x800/png?text=Hundru+Falls',
    array['https://placehold.co/800x600/png?text=Hundru+Falls+1', 'https://placehold.co/800x600/png?text=Hundru+Falls+2'],
    true,
    'October to March',
    0,
    'published'
  ),
  (
    'Dassam Falls',
    'dassam-falls',
    'A popular waterfall destination known for its layered cascade and green surroundings.',
    'Dassam Falls is represented as demo tourism content for route, card, and detail page testing.',
    'Ranchi',
    'waterfall',
    23.3710,
    85.4414,
    'https://placehold.co/1200x800/png?text=Dassam+Falls',
    array['https://placehold.co/800x600/png?text=Dassam+Falls+1', 'https://placehold.co/800x600/png?text=Dassam+Falls+2'],
    true,
    'July to February',
    0,
    'published'
  ),
  (
    'Jonha Falls',
    'jonha-falls',
    'A scenic waterfall destination often associated with a calm forest setting.',
    'Jonha Falls is a demo destination entry for the Jharkhand tourism foundation and may be refined later with official details.',
    'Ranchi',
    'waterfall',
    23.4060,
    85.4850,
    'https://placehold.co/1200x800/png?text=Jonha+Falls',
    array['https://placehold.co/800x600/png?text=Jonha+Falls+1', 'https://placehold.co/800x600/png?text=Jonha+Falls+2'],
    true,
    'September to February',
    0,
    'published'
  ),
  (
    'Netarhat',
    'netarhat',
    'A hill station destination often associated with sunrise views and cool weather.',
    'Netarhat is included as a demo eco destination to support future route planning and regional discovery.',
    'Latehar',
    'eco',
    23.4790,
    84.2640,
    'https://placehold.co/1200x800/png?text=Netarhat',
    array['https://placehold.co/800x600/png?text=Netarhat+1', 'https://placehold.co/800x600/png?text=Netarhat+2'],
    true,
    'October to March',
    0,
    'published'
  ),
  (
    'Betla National Park',
    'betla-national-park',
    'A major wildlife destination and forest landscape for nature-focused travel.',
    'Betla National Park is represented as a wildlife destination in the seed set for public browsing and later map integration.',
    'Latehar',
    'wildlife',
    23.8300,
    84.1300,
    'https://placehold.co/1200x800/png?text=Betla+National+Park',
    array['https://placehold.co/800x600/png?text=Betla+1', 'https://placehold.co/800x600/png?text=Betla+2'],
    true,
    'November to April',
    50,
    'published'
  ),
  (
    'Patratu Valley',
    'patratu-valley',
    'A scenic valley route known for winding roads and broad landscape views.',
    'Patratu Valley is seeded as an adventure-oriented destination to support route discovery and itinerary features later.',
    'Ramgarh',
    'adventure',
    23.6380,
    85.3610,
    'https://placehold.co/1200x800/png?text=Patratu+Valley',
    array['https://placehold.co/800x600/png?text=Patratu+Valley+1', 'https://placehold.co/800x600/png?text=Patratu+Valley+2'],
    true,
    'October to February',
    0,
    'published'
  ),
  (
    'Baidyanath Dham, Deoghar',
    'baidyanath-dham-deoghar',
    'A major religious destination in Deoghar with long-standing pilgrimage significance.',
    'This demo entry represents a religious tourism point and should be validated against official source data later.',
    'Deoghar',
    'religious',
    24.4860,
    86.6980,
    'https://placehold.co/1200x800/png?text=Baidyanath+Dham',
    array['https://placehold.co/800x600/png?text=Baidyanath+Dham+1', 'https://placehold.co/800x600/png?text=Baidyanath+Dham+2'],
    false,
    'All year',
    0,
    'published'
  ),
  (
    'Rock Garden, Ranchi',
    'rock-garden-ranchi',
    'A city-side attraction that blends landscape design and local sightseeing.',
    'Rock Garden is included here as a heritage-style urban attraction for dashboard and search testing.',
    'Ranchi',
    'heritage',
    23.3620,
    85.3270,
    'https://placehold.co/1200x800/png?text=Rock+Garden+Ranchi',
    array['https://placehold.co/800x600/png?text=Rock+Garden+1', 'https://placehold.co/800x600/png?text=Rock+Garden+2'],
    false,
    'October to March',
    20,
    'published'
  ),
  (
    'Tribal Museum, Ranchi',
    'tribal-museum-ranchi',
    'A cultural learning destination focused on tribal heritage and regional identity.',
    'This demo entry supports the tribal culture category and can later link to educational content and local storytelling.',
    'Ranchi',
    'tribal_culture',
    23.3640,
    85.3210,
    'https://placehold.co/1200x800/png?text=Tribal+Museum+Ranchi',
    array['https://placehold.co/800x600/png?text=Tribal+Museum+1', 'https://placehold.co/800x600/png?text=Tribal+Museum+2'],
    false,
    'All year',
    10,
    'published'
  ),
  (
    'Saranda Forest',
    'saranda-forest',
    'A forest-rich landscape suited for eco and wildlife-oriented discovery.',
    'Saranda Forest is seeded as a wildlife and eco destination to support future sustainability and exploration features.',
    'West Singhbhum',
    'wildlife',
    22.3100,
    85.3400,
    'https://placehold.co/1200x800/png?text=Saranda+Forest',
    array['https://placehold.co/800x600/png?text=Saranda+Forest+1', 'https://placehold.co/800x600/png?text=Saranda+Forest+2'],
    true,
    'October to March',
    0,
    'published'
  ),
  (
    'Lodh Falls',
    'lodh-falls',
    'A tall waterfall destination often cited among the scenic highlights of the region.',
    'Lodh Falls is a demo waterfall entry for future search, map, and itinerary workflows.',
    'Latehar',
    'waterfall',
    23.7320,
    84.6610,
    'https://placehold.co/1200x800/png?text=Lodh+Falls',
    array['https://placehold.co/800x600/png?text=Lodh+Falls+1', 'https://placehold.co/800x600/png?text=Lodh+Falls+2'],
    true,
    'July to February',
    0,
    'published'
  ),
  (
    'Pahari Mandir, Ranchi',
    'pahari-mandir-ranchi',
    'A well-known religious site with a strong city landmark presence.',
    'Pahari Mandir is included as a religious destination seed for Jharkhand public browsing.',
    'Ranchi',
    'religious',
    23.3770,
    85.3115,
    'https://placehold.co/1200x800/png?text=Pahari+Mandir',
    array['https://placehold.co/800x600/png?text=Pahari+Mandir+1', 'https://placehold.co/800x600/png?text=Pahari+Mandir+2'],
    false,
    'All year',
    0,
    'published'
  ),
  (
    'McCluskieganj',
    'mccluskieganj',
    'A heritage-rich settlement known for its colonial-era character and quiet surroundings.',
    'McCluskieganj is used here as a heritage destination example for the platform foundation.',
    'Ranchi',
    'heritage',
    23.8910,
    84.9850,
    'https://placehold.co/1200x800/png?text=McCluskieganj',
    array['https://placehold.co/800x600/png?text=McCluskieganj+1', 'https://placehold.co/800x600/png?text=McCluskieganj+2'],
    false,
    'October to March',
    0,
    'published'
  )
on conflict (slug) do update set
  name = excluded.name,
  short_description = excluded.short_description,
  description = excluded.description,
  district = excluded.district,
  category = excluded.category,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  cover_image = excluded.cover_image,
  gallery = excluded.gallery,
  eco_zone = excluded.eco_zone,
  best_time = excluded.best_time,
  entry_fee = excluded.entry_fee,
  status = excluded.status;

